version: '3.8'

services:
  app:
    build: .
    command: daphne -b 0.0.0.0 -p 8000 order.asgi:application
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - channel_redis
    restart: 'on-failure'
  nginx:
    image: nginx:latest
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - app
    restart: 'on-failure'
  channel_redis:
    image: redis:latest
    ports:
      - '6379:6379'
    restart: 'on-failure'
volumes:
  staticfiles:
  media:
