version: '3.8'

services:
  app:
    build: .
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    depends_on:
      - channel_redis
      - db
    restart: 'on-failure'
  nginx:
    image: 'nginx:latest'
    ports:
      - '80:80'
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./staticfiles:/app/staticfiles
      - ./media:/app/media
    depends_on:
      - app
    restart: 'on-failure'
  channel_redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'
    restart: 'on-failure'
  db:
    image: 'postgres:latest'
    environment:
      POSTGRES_DB: orderdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: 'on-failure'
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db
volumes:
  staticfiles:
  media:
  postgres_data:
